#include "algorithm/advance_vector.hpp"
#include "algorithm/numeric.hpp"
#include "algorithm/range_wrappers.hpp"
#include "algorithm/set_ops.hpp"
#include "algorithm/split.hpp"
#include "algorithm/traits.hpp"
#include "algorithm/utils.hpp"
#include "algorithm/variance.hpp"
